python run_model.py \
    --do_train \
    --do_lower_case \
    --data_dir ./data/misogyny_EN \
    --bert_model bert-base-uncased \
    --max_seq_length 64 \
    --train_batch_size 32 \
    --learning_rate 2e-5 \
    --num_train_epochs 3 \
    --early_stop 2 \
    --output_dir runs/misog_42 \
    --seed 42 \
    --task_name misog \
    --reg_explanations \
    --nb_range 5 \
    --sample_n 5 \
    --negative_weight 0.125 \
    --reg_strength 0.1 \
    --lm_dir runs/lm_misog \
    --hiex_add_itself \
    --neutral_words_file data/identity_ws_new.csv
